# Generated by Django 2.0 on 2020-05-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='title_bound',
            field=models.IntegerField(verbose_name='Yorum Sınırı'),
        ),
    ]
