# Generated by Django 2.0 on 2020-05-04 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('title', '0002_auto_20200504_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=200, verbose_name='Yapılan Yorum')),
                ('sentiment', models.CharField(max_length=20, verbose_name='Duygu Analizi')),
                ('comment_date', models.DateTimeField(auto_now_add=True, verbose_name='Yorum Yapma Tarihi')),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yorum Yapan')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='title.Title', verbose_name='Başlık')),
            ],
        ),
    ]
