# Generated by Django 2.0 on 2020-05-04 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=1000, null=True, verbose_name='Hakkımızda')),
                ('profile_photo', models.ImageField(blank=True, upload_to='user_profile', verbose_name='Profil Fotoğrafı')),
                ('sector', models.CharField(choices=[(None, 'Sektör Seçiniz'), ('belediye', 'BELEDİYE'), ('eğitim', 'EĞİTİM'), ('eğlence', 'EĞLENCE'), ('girişim', 'GİRİŞİM'), ('hizmet', 'HİZMET'), ('sağlık', 'SAĞLIK'), ('sanayi', 'SANAYİ'), ('sivil toplum örgütü', 'SİVİL TOPLUM ÖRGÜTÜ'), ('teknoloji', 'TEKNOLOJİ')], max_length=20, null=True, verbose_name='Sektör')),
                ('email_confirmation', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Kurumsal Kullanici Profili',
            },
        ),
        migrations.CreateModel(
            name='PersonalUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ad')),
                ('surname', models.CharField(max_length=25, verbose_name='Soyad')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Profil Fotoğrafı')),
                ('age', models.IntegerField(verbose_name='Yaş')),
                ('sex', models.CharField(choices=[(None, 'Cinsiyet Seçiniz'), ('diğer', 'DİĞER'), ('erkek', 'ERKEK'), ('kadın', 'KADIN')], max_length=6, null=True, verbose_name='Cinsiyet')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Bireysel Kullanici Profili',
            },
        ),
        migrations.CreateModel(
            name='user_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enterprises', models.BooleanField(default=False)),
                ('is_personals', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
