# Generated by Django 2.0 on 2020-05-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200504_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaluserprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='user_profile', verbose_name='Profil Fotoğrafı'),
        ),
    ]
